# Generated by Django 2.2.5 on 2020-06-24 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('avatar', models.ImageField(null=True, upload_to='user_avatar')),
                ('lastname1', models.CharField(max_length=30)),
                ('lastname2', models.CharField(max_length=30)),
                ('ocupation', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Dr.', 'Doctor'), ('Dra.', 'Doctora'), ('Msc.', 'Master en Ciencias'), ('Lic.', 'Licenciado'), ('Ing.', 'Ingeniero'), ('Téc.', 'Técnico')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForecastCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Centros',
            },
        ),
        migrations.CreateModel(
            name='AppUserContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('EMAIL', 'Correo electrónico'), ('PHONE', 'Teléfono'), ('CELLPHONE', 'Celular')], max_length=20, null=True)),
                ('contact', models.CharField(max_length=20, null=True)),
                ('appuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='security.AppUser')),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='forecast_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='security.ForecastCenter'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
