# Generated by Django 2.2.5 on 2020-06-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusercontact',
            name='contact_type',
            field=models.CharField(choices=[('CELLPHONE', 'Celular'), ('PHONE', 'Teléfono'), ('EMAIL', 'Correo electrónico')], max_length=20, null=True),
        ),
    ]
