# Generated by Django 2.2.5 on 2020-06-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_auto_20200624_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusercontact',
            name='contact_type',
            field=models.CharField(choices=[('PHONE', 'Teléfono'), ('CELLPHONE', 'Celular'), ('EMAIL', 'Correo electrónico')], max_length=20, null=True),
        ),
    ]
