# Generated by Django 2.2.5 on 2020-07-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_auto_20200712_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusercontact',
            name='contact_type',
            field=models.CharField(choices=[('PHONE', 'Teléfono'), ('EMAIL', 'Correo electrónico'), ('CELLPHONE', 'Celular')], max_length=20, null=True),
        ),
    ]
