# Generated by Django 2.2.5 on 2020-06-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national_forecast_center', '0002_auto_20200624_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dp10',
            name='code',
            field=models.CharField(blank=True, default='FECU42 MUHV', max_length=20, null=True),
        ),
    ]
