# Generated by Django 2.2.5 on 2020-06-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national_forecast_center', '0003_auto_20200624_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='secondary_author', to='security.AppUser'),
        ),
    ]
