# Generated by Django 2.2.5 on 2020-06-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national_forecast_center', '0005_auto_20200624_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phenomena',
            name='type_of_phenomena',
            field=models.CharField(blank=True, choices=[('TT', 'Tormenta Tropical'), ('CT', 'Ciclón Tropical'), ('DT', 'Depresión Tropical')], max_length=255, null=True),
        ),
    ]
