# Generated by Django 2.2.5 on 2020-07-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national_forecast_center', '0007_auto_20200712_0829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pttn',
            options={'verbose_name_plural': 'Pronóstico del Tiempo para la Tarde y la Noche'},
        ),
        migrations.AddField(
            model_name='pttn',
            name='code',
            field=models.CharField(blank=True, default='FECU42 MUHV', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='phenomena',
            name='type_of_phenomena',
            field=models.CharField(blank=True, choices=[('TT', 'Tormenta Tropical'), ('CT', 'Ciclón Tropical'), ('DT', 'Depresión Tropical')], max_length=255, null=True),
        ),
    ]
