# Generated by Django 2.2.5 on 2020-07-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national_forecast_center', '0008_auto_20200712_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phenomena',
            name='type_of_phenomena',
            field=models.CharField(blank=True, choices=[('DT', 'Depresión Tropical'), ('TT', 'Tormenta Tropical'), ('CT', 'Ciclón Tropical')], max_length=255, null=True),
        ),
    ]
